#!/usr/bin/env python3
"""Convert a madge/pydeps graph.json into a deterministic Mermaid flowchart.

Part of the Codebase Context Kit. Reads graph.json (the dependency graph emitted by
`madge --json` or `pydeps --show-deps`) and writes a `flowchart LR` to stdout. The
output is fully sorted so committed deltas show cleanly in PR diffs. The generated
graph.mmd is machine output — never hand-edit it; it is regenerated from source every turn.

Usage: graph_to_mermaid.py [graph.json]   (reads stdin if no path is given)
"""
import json
import re
import sys

MAX_EDGES = 2000  # lift Mermaid's default (500) so large graphs still render

HEADER_LINES = [
    "%% Structure graph — the dependency wiring, GENERATED FROM SOURCE every turn.",
    "%% Machine output of .claude/hooks/graph_to_mermaid.py (from graph.json) — DO NOT EDIT BY HAND.",
    "%% Committed so dependency deltas surface in PR diffs; regenerated by update-structure.sh.",
]

_UNSAFE = re.compile(r"[^0-9A-Za-z_]+")


def iter_edges(data):
    """Yield (src, dst) module pairs from either the madge or pydeps JSON shape."""
    values = list(data.values())
    is_pydeps = any(isinstance(v, dict) for v in values)
    if is_pydeps:
        # Forward `imports` is preferred; older pydeps may only give `imported_by`.
        has_imports = any(isinstance(v, dict) and v.get("imports") for v in values)
        for mod, info in data.items():
            if not isinstance(info, dict):
                continue
            if has_imports:
                for dep in info.get("imports") or []:
                    yield mod, dep
            else:
                for parent in info.get("imported_by") or []:
                    yield parent, mod
    else:  # madge: { "mod": ["dep", ...] }
        for mod, deps in data.items():
            for dep in deps or []:
                yield mod, dep


def collect(data):
    """Return (nodes, edges). Every top-level module is a node so isolated files show."""
    nodes = set(data.keys())
    edges = set()
    for src, dst in iter_edges(data):
        nodes.add(src)
        nodes.add(dst)
        if src != dst:  # a self-import adds no information
            edges.add((src, dst))
    return nodes, edges


def assign_ids(nodes):
    """Map each module to a safe, unique, deterministic Mermaid node id."""
    ids, used = {}, set()
    for mod in sorted(nodes):
        base = _UNSAFE.sub("_", mod).strip("_") or "node"
        if base[0].isdigit():
            base = "m_" + base
        cand, n = base, 2
        while cand in used:
            cand, n = "%s_%d" % (base, n), n + 1
        used.add(cand)
        ids[mod] = cand
    return ids


def render(data):
    nodes, edges = collect(data)
    lines = ["%%{init: {'maxEdges': " + str(MAX_EDGES) + "}}%%"]
    lines += HEADER_LINES
    lines.append("flowchart LR")
    if not nodes:
        lines.append('    empty["(no modules detected)"]')
        return "\n".join(lines) + "\n"
    ids = assign_ids(nodes)
    for mod in sorted(nodes):
        lines.append('    %s["%s"]' % (ids[mod], mod.replace('"', "&quot;")))
    for src, dst in sorted(edges):
        lines.append("    %s --> %s" % (ids[src], ids[dst]))
    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) > 1:
        with open(sys.argv[1], encoding="utf-8") as fh:
            data = json.load(fh)
    else:
        data = json.load(sys.stdin)
    if not isinstance(data, dict):
        raise SystemExit("graph_to_mermaid: expected a JSON object at the top level")
    sys.stdout.write(render(data))


if __name__ == "__main__":
    main()
